[tool.poetry]
name = "vtuber-livechat-dataset"
version = "0.1.0"
description = ""
authors = ["Yasuaki Uechi <y@uechi.io>"]

[tool.poetry.dependencies]
python = "^3.9"
numpy = "^1.20.1"
matplotlib = "^3.3.4"
pandas = "^1.2.3"
pymongo = "^3.11.3"

[tool.poetry.dev-dependencies]
ipykernel = "^5.5.0"
yapf = "^0.31.0"
kaggle = "^1.5.12"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
